### PR TITLE
Restructure app

### PR DESCRIPTION
**Pull request by DavidHernandez**
* Divide to model, update, view
* Add router
* Add 404 page

### CODE REVIEW

**Comment by DavidHernandez** [comment]
@amitaibu I think this one is ready.

**Comment by DavidHernandez** [comment]
Tests are passing locally:
generator-elm
And screenshot of how does it look:
counter-elm

**Comment by amitaibu** [comment]
Lets remove the footer, and it should be good to go.

**Comment by amitaibu** [comment]
Merged and published:

`gcm && gl && npm version minor && git push --tags && git push && npm publish ./`

gcm = git checkout master
gl = git pull

**Comment by amitaibu** [comment]
@DavidHernandez what is your npm username?

**Comment by DavidHernandez** [comment]
@amitaibu my npm username is davidhernandez

**Comment by amitaibu** [comment]
Access granted on npm. You can use the above command https://github.com/Gizra/generator-elmlang/pull/35#issuecomment-250929344 whenever you release stuff.

**Pull request merged**
