### PR TITLE
Upgrades elm-test to the last version.

### PR DESCRIPTION
**Pull request by DavidHernandez**
elm-test has been upgraded to the last version. Now it comes with cool colors!
### Green tests

green-tests
### Red tests

test-failed

### CODE REVIEW

**Comment by DavidHernandez** [comment]
@amitaibu maybe you want to have a review it.

**Comment by amitaibu** [comment]
[This](https://github.com/Gizra/generator-elmlang/blob/f3866f5cfb89c377d41e025005e0b6caa34e07f0/generators/app/templates/runTests.js#L9-L11) part in `.travis.yml` should probably change, as we rely on casperJs to check for us if the tests passed or not.

(The passing travis of this repo is of the yo generator, not the scaffolded one - which we have [here](https://github.com/Gizra/generator-elmlang-example)

**Comment by amitaibu** [comment]
👍

**Comment by amitaibu** [comment]
Thanks. Published a new version in npm?

**Comment by DavidHernandez** [comment]
Yes, I published it as a major release (2.0.0) as the last Elm version will break the existing tests.

**Comment by amitaibu** [comment]
Thanks.

**Pull request merged**
