### PR TITLE
Test Elm Platform semver against supported range

### PR DESCRIPTION
**Pull request by DigitalMachinist**
#31

Added semver package from npm to handle validation of Elm Platform semver during generator install process.
Added validateEnv function to check Elm Platform semver before files are installed and throw various exceptions if the version isn't within appropriate bounds.
Fixed a spelling error: 'Skiped installation' -> 'Skipped installation'
Adjusted inconsistent line spacing above writing function.

### CODE REVIEW

**Comment by amitaibu** [comment]
Cool!

> Looks like it failed Travis, but that's just because my code emits an error if elm doesn't appear to be installed

Maybe you can add `- npm install -g elm@0.17.0` to travis so tests will come back green.

**Comment by DigitalMachinist** [comment]
I'm not very experienced with Travis configuration, but the docs make it look like the `npm install -g elm@0.17.0` should belong to an install hook. Hope I did it right... ;)

**Comment by DigitalMachinist** [comment]
Well, I wasn't expecting mocha to be missing...

**Comment by DigitalMachinist** [comment]
Great! Travis is up and working again. Let me know what you think.

Anyway, hopefully I can sit back and make some use of this generator soon!

**Comment by amitaibu** [comment]
Awesome work, thanks!

Published `v1.2.0`

**Comment by DigitalMachinist** [comment]
No problem. Glad I could save some trouble for others wanting to dive in and try this out!

**Pull request merged**
